-- Auto-generated by WezTerm - DO NOT EDIT
-- Theme: Gooey (Gogh),
-- Generated: 2026-02-03 23:06:08

return {
  name = "Gooey (Gogh)",
  bg = "#0d101b",
  fg = "#ebeef9",
  cursor = "#ebeef9",
  cursor_fg = "#0d101b",
  selection_bg = "#444444",
  selection_fg = "#ebeef9",

  -- ANSI colors
  black = "#000009",
  red = "#bb4f6c",
  green = "#72ccae",
  yellow = "#c65e3d",
  blue = "#58b6ca",
  magenta = "#6488c4",
  cyan = "#8d84c6",
  white = "#858893",

  -- Bright colors
  bright_black = "#1f222d",
  bright_red = "#ee829f",
  bright_green = "#a5ffe1",
  bright_yellow = "#f99170",
  bright_blue = "#8be9fd",
  bright_magenta = "#97bbf7",
  bright_cyan = "#c0b7f9",
  bright_white = "#ffffff",

  -- ANSI array for terminal colors
  ansi = {
    "#000009",
    "#bb4f6c",
    "#72ccae",
    "#c65e3d",
    "#58b6ca",
    "#6488c4",
    "#8d84c6",
    "#858893",
  },
  brights = {
    "#1f222d",
    "#ee829f",
    "#a5ffe1",
    "#f99170",
    "#8be9fd",
    "#97bbf7",
    "#c0b7f9",
    "#ffffff",
  },
}